/**
 * Autogenerated by Thrift Compiler (0.13.0)
 *
 * DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
 *  @generated
 */

@SuppressWarnings({"cast", "rawtypes", "serial", "unchecked", "unused"})
@javax.annotation.Generated(value = "Autogenerated by Thrift Compiler (0.13.0)", date = "2020-06-21")
public class Forca {

  /**
   * Ahh, now onto the cool part, defining a service. Services just need a name
   * and can optionally inherit from another service using the extends keyword.
   */
  public interface Iface {

    /**
     * A method definition looks like C code. It has a return type, arguments,
     * and optionally a list of exceptions that it may throw. Note that argument
     * lists and exception lists are specified using the exact same syntax as
     * field lists in struct or exception definitions.
     * 
     * @param letra
     * @param jogador
     */
    public Placar gerar_rodada(Letra letra, idJogador jogador) throws org.apache.thrift.TException;

    public Placar exibir_rodada(idJogador jogador) throws org.apache.thrift.TException;

  }

  public interface AsyncIface {

    public void gerar_rodada(Letra letra, idJogador jogador, org.apache.thrift.async.AsyncMethodCallback<Placar> resultHandler) throws org.apache.thrift.TException;

    public void exibir_rodada(idJogador jogador, org.apache.thrift.async.AsyncMethodCallback<Placar> resultHandler) throws org.apache.thrift.TException;

  }

  public static class Client extends org.apache.thrift.TServiceClient implements Iface {
    public static class Factory implements org.apache.thrift.TServiceClientFactory<Client> {
      public Factory() {}
      public Client getClient(org.apache.thrift.protocol.TProtocol prot) {
        return new Client(prot);
      }
      public Client getClient(org.apache.thrift.protocol.TProtocol iprot, org.apache.thrift.protocol.TProtocol oprot) {
        return new Client(iprot, oprot);
      }
    }

    public Client(org.apache.thrift.protocol.TProtocol prot)
    {
      super(prot, prot);
    }

    public Client(org.apache.thrift.protocol.TProtocol iprot, org.apache.thrift.protocol.TProtocol oprot) {
      super(iprot, oprot);
    }

    public Placar gerar_rodada(Letra letra, idJogador jogador) throws org.apache.thrift.TException
    {
      send_gerar_rodada(letra, jogador);
      return recv_gerar_rodada();
    }

    public void send_gerar_rodada(Letra letra, idJogador jogador) throws org.apache.thrift.TException
    {
      gerar_rodada_args args = new gerar_rodada_args();
      args.setLetra(letra);
      args.setJogador(jogador);
      sendBase("gerar_rodada", args);
    }

    public Placar recv_gerar_rodada() throws org.apache.thrift.TException
    {
      gerar_rodada_result result = new gerar_rodada_result();
      receiveBase(result, "gerar_rodada");
      if (result.isSetSuccess()) {
        return result.success;
      }
      throw new org.apache.thrift.TApplicationException(org.apache.thrift.TApplicationException.MISSING_RESULT, "gerar_rodada failed: unknown result");
    }

    public Placar exibir_rodada(idJogador jogador) throws org.apache.thrift.TException
    {
      send_exibir_rodada(jogador);
      return recv_exibir_rodada();
    }

    public void send_exibir_rodada(idJogador jogador) throws org.apache.thrift.TException
    {
      exibir_rodada_args args = new exibir_rodada_args();
      args.setJogador(jogador);
      sendBase("exibir_rodada", args);
    }

    public Placar recv_exibir_rodada() throws org.apache.thrift.TException
    {
      exibir_rodada_result result = new exibir_rodada_result();
      receiveBase(result, "exibir_rodada");
      if (result.isSetSuccess()) {
        return result.success;
      }
      throw new org.apache.thrift.TApplicationException(org.apache.thrift.TApplicationException.MISSING_RESULT, "exibir_rodada failed: unknown result");
    }

  }
  public static class AsyncClient extends org.apache.thrift.async.TAsyncClient implements AsyncIface {
    public static class Factory implements org.apache.thrift.async.TAsyncClientFactory<AsyncClient> {
      private org.apache.thrift.async.TAsyncClientManager clientManager;
      private org.apache.thrift.protocol.TProtocolFactory protocolFactory;
      public Factory(org.apache.thrift.async.TAsyncClientManager clientManager, org.apache.thrift.protocol.TProtocolFactory protocolFactory) {
        this.clientManager = clientManager;
        this.protocolFactory = protocolFactory;
      }
      public AsyncClient getAsyncClient(org.apache.thrift.transport.TNonblockingTransport transport) {
        return new AsyncClient(protocolFactory, clientManager, transport);
      }
    }

    public AsyncClient(org.apache.thrift.protocol.TProtocolFactory protocolFactory, org.apache.thrift.async.TAsyncClientManager clientManager, org.apache.thrift.transport.TNonblockingTransport transport) {
      super(protocolFactory, clientManager, transport);
    }

    public void gerar_rodada(Letra letra, idJogador jogador, org.apache.thrift.async.AsyncMethodCallback<Placar> resultHandler) throws org.apache.thrift.TException {
      checkReady();
      gerar_rodada_call method_call = new gerar_rodada_call(letra, jogador, resultHandler, this, ___protocolFactory, ___transport);
      this.___currentMethod = method_call;
      ___manager.call(method_call);
    }

    public static class gerar_rodada_call extends org.apache.thrift.async.TAsyncMethodCall<Placar> {
      private Letra letra;
      private idJogador jogador;
      public gerar_rodada_call(Letra letra, idJogador jogador, org.apache.thrift.async.AsyncMethodCallback<Placar> resultHandler, org.apache.thrift.async.TAsyncClient client, org.apache.thrift.protocol.TProtocolFactory protocolFactory, org.apache.thrift.transport.TNonblockingTransport transport) throws org.apache.thrift.TException {
        super(client, protocolFactory, transport, resultHandler, false);
        this.letra = letra;
        this.jogador = jogador;
      }

      public void write_args(org.apache.thrift.protocol.TProtocol prot) throws org.apache.thrift.TException {
        prot.writeMessageBegin(new org.apache.thrift.protocol.TMessage("gerar_rodada", org.apache.thrift.protocol.TMessageType.CALL, 0));
        gerar_rodada_args args = new gerar_rodada_args();
        args.setLetra(letra);
        args.setJogador(jogador);
        args.write(prot);
        prot.writeMessageEnd();
      }

      public Placar getResult() throws org.apache.thrift.TException {
        if (getState() != org.apache.thrift.async.TAsyncMethodCall.State.RESPONSE_READ) {
          throw new java.lang.IllegalStateException("Method call not finished!");
        }
        org.apache.thrift.transport.TMemoryInputTransport memoryTransport = new org.apache.thrift.transport.TMemoryInputTransport(getFrameBuffer().array());
        org.apache.thrift.protocol.TProtocol prot = client.getProtocolFactory().getProtocol(memoryTransport);
        return (new Client(prot)).recv_gerar_rodada();
      }
    }

    public void exibir_rodada(idJogador jogador, org.apache.thrift.async.AsyncMethodCallback<Placar> resultHandler) throws org.apache.thrift.TException {
      checkReady();
      exibir_rodada_call method_call = new exibir_rodada_call(jogador, resultHandler, this, ___protocolFactory, ___transport);
      this.___currentMethod = method_call;
      ___manager.call(method_call);
    }

    public static class exibir_rodada_call extends org.apache.thrift.async.TAsyncMethodCall<Placar> {
      private idJogador jogador;
      public exibir_rodada_call(idJogador jogador, org.apache.thrift.async.AsyncMethodCallback<Placar> resultHandler, org.apache.thrift.async.TAsyncClient client, org.apache.thrift.protocol.TProtocolFactory protocolFactory, org.apache.thrift.transport.TNonblockingTransport transport) throws org.apache.thrift.TException {
        super(client, protocolFactory, transport, resultHandler, false);
        this.jogador = jogador;
      }

      public void write_args(org.apache.thrift.protocol.TProtocol prot) throws org.apache.thrift.TException {
        prot.writeMessageBegin(new org.apache.thrift.protocol.TMessage("exibir_rodada", org.apache.thrift.protocol.TMessageType.CALL, 0));
        exibir_rodada_args args = new exibir_rodada_args();
        args.setJogador(jogador);
        args.write(prot);
        prot.writeMessageEnd();
      }

      public Placar getResult() throws org.apache.thrift.TException {
        if (getState() != org.apache.thrift.async.TAsyncMethodCall.State.RESPONSE_READ) {
          throw new java.lang.IllegalStateException("Method call not finished!");
        }
        org.apache.thrift.transport.TMemoryInputTransport memoryTransport = new org.apache.thrift.transport.TMemoryInputTransport(getFrameBuffer().array());
        org.apache.thrift.protocol.TProtocol prot = client.getProtocolFactory().getProtocol(memoryTransport);
        return (new Client(prot)).recv_exibir_rodada();
      }
    }

  }

  public static class Processor<I extends Iface> extends org.apache.thrift.TBaseProcessor<I> implements org.apache.thrift.TProcessor {
    private static final org.slf4j.Logger _LOGGER = org.slf4j.LoggerFactory.getLogger(Processor.class.getName());
    public Processor(I iface) {
      super(iface, getProcessMap(new java.util.HashMap<java.lang.String, org.apache.thrift.ProcessFunction<I, ? extends org.apache.thrift.TBase>>()));
    }

    protected Processor(I iface, java.util.Map<java.lang.String, org.apache.thrift.ProcessFunction<I, ? extends org.apache.thrift.TBase>> processMap) {
      super(iface, getProcessMap(processMap));
    }

    private static <I extends Iface> java.util.Map<java.lang.String,  org.apache.thrift.ProcessFunction<I, ? extends org.apache.thrift.TBase>> getProcessMap(java.util.Map<java.lang.String, org.apache.thrift.ProcessFunction<I, ? extends  org.apache.thrift.TBase>> processMap) {
      processMap.put("gerar_rodada", new gerar_rodada());
      processMap.put("exibir_rodada", new exibir_rodada());
      return processMap;
    }

    public static class gerar_rodada<I extends Iface> extends org.apache.thrift.ProcessFunction<I, gerar_rodada_args> {
      public gerar_rodada() {
        super("gerar_rodada");
      }

      public gerar_rodada_args getEmptyArgsInstance() {
        return new gerar_rodada_args();
      }

      protected boolean isOneway() {
        return false;
      }

      @Override
      protected boolean rethrowUnhandledExceptions() {
        return false;
      }

      public gerar_rodada_result getResult(I iface, gerar_rodada_args args) throws org.apache.thrift.TException {
        gerar_rodada_result result = new gerar_rodada_result();
        result.success = iface.gerar_rodada(args.letra, args.jogador);
        return result;
      }
    }

    public static class exibir_rodada<I extends Iface> extends org.apache.thrift.ProcessFunction<I, exibir_rodada_args> {
      public exibir_rodada() {
        super("exibir_rodada");
      }

      public exibir_rodada_args getEmptyArgsInstance() {
        return new exibir_rodada_args();
      }

      protected boolean isOneway() {
        return false;
      }

      @Override
      protected boolean rethrowUnhandledExceptions() {
        return false;
      }

      public exibir_rodada_result getResult(I iface, exibir_rodada_args args) throws org.apache.thrift.TException {
        exibir_rodada_result result = new exibir_rodada_result();
        result.success = iface.exibir_rodada(args.jogador);
        return result;
      }
    }

  }

  public static class AsyncProcessor<I extends AsyncIface> extends org.apache.thrift.TBaseAsyncProcessor<I> {
    private static final org.slf4j.Logger _LOGGER = org.slf4j.LoggerFactory.getLogger(AsyncProcessor.class.getName());
    public AsyncProcessor(I iface) {
      super(iface, getProcessMap(new java.util.HashMap<java.lang.String, org.apache.thrift.AsyncProcessFunction<I, ? extends org.apache.thrift.TBase, ?>>()));
    }

    protected AsyncProcessor(I iface, java.util.Map<java.lang.String,  org.apache.thrift.AsyncProcessFunction<I, ? extends  org.apache.thrift.TBase, ?>> processMap) {
      super(iface, getProcessMap(processMap));
    }

    private static <I extends AsyncIface> java.util.Map<java.lang.String,  org.apache.thrift.AsyncProcessFunction<I, ? extends  org.apache.thrift.TBase,?>> getProcessMap(java.util.Map<java.lang.String,  org.apache.thrift.AsyncProcessFunction<I, ? extends  org.apache.thrift.TBase, ?>> processMap) {
      processMap.put("gerar_rodada", new gerar_rodada());
      processMap.put("exibir_rodada", new exibir_rodada());
      return processMap;
    }

    public static class gerar_rodada<I extends AsyncIface> extends org.apache.thrift.AsyncProcessFunction<I, gerar_rodada_args, Placar> {
      public gerar_rodada() {
        super("gerar_rodada");
      }

      public gerar_rodada_args getEmptyArgsInstance() {
        return new gerar_rodada_args();
      }

      public org.apache.thrift.async.AsyncMethodCallback<Placar> getResultHandler(final org.apache.thrift.server.AbstractNonblockingServer.AsyncFrameBuffer fb, final int seqid) {
        final org.apache.thrift.AsyncProcessFunction fcall = this;
        return new org.apache.thrift.async.AsyncMethodCallback<Placar>() { 
          public void onComplete(Placar o) {
            gerar_rodada_result result = new gerar_rodada_result();
            result.success = o;
            try {
              fcall.sendResponse(fb, result, org.apache.thrift.protocol.TMessageType.REPLY,seqid);
            } catch (org.apache.thrift.transport.TTransportException e) {
              _LOGGER.error("TTransportException writing to internal frame buffer", e);
              fb.close();
            } catch (java.lang.Exception e) {
              _LOGGER.error("Exception writing to internal frame buffer", e);
              onError(e);
            }
          }
          public void onError(java.lang.Exception e) {
            byte msgType = org.apache.thrift.protocol.TMessageType.REPLY;
            org.apache.thrift.TSerializable msg;
            gerar_rodada_result result = new gerar_rodada_result();
            if (e instanceof org.apache.thrift.transport.TTransportException) {
              _LOGGER.error("TTransportException inside handler", e);
              fb.close();
              return;
            } else if (e instanceof org.apache.thrift.TApplicationException) {
              _LOGGER.error("TApplicationException inside handler", e);
              msgType = org.apache.thrift.protocol.TMessageType.EXCEPTION;
              msg = (org.apache.thrift.TApplicationException)e;
            } else {
              _LOGGER.error("Exception inside handler", e);
              msgType = org.apache.thrift.protocol.TMessageType.EXCEPTION;
              msg = new org.apache.thrift.TApplicationException(org.apache.thrift.TApplicationException.INTERNAL_ERROR, e.getMessage());
            }
            try {
              fcall.sendResponse(fb,msg,msgType,seqid);
            } catch (java.lang.Exception ex) {
              _LOGGER.error("Exception writing to internal frame buffer", ex);
              fb.close();
            }
          }
        };
      }

      protected boolean isOneway() {
        return false;
      }

      public void start(I iface, gerar_rodada_args args, org.apache.thrift.async.AsyncMethodCallback<Placar> resultHandler) throws org.apache.thrift.TException {
        iface.gerar_rodada(args.letra, args.jogador,resultHandler);
      }
    }

    public static class exibir_rodada<I extends AsyncIface> extends org.apache.thrift.AsyncProcessFunction<I, exibir_rodada_args, Placar> {
      public exibir_rodada() {
        super("exibir_rodada");
      }

      public exibir_rodada_args getEmptyArgsInstance() {
        return new exibir_rodada_args();
      }

      public org.apache.thrift.async.AsyncMethodCallback<Placar> getResultHandler(final org.apache.thrift.server.AbstractNonblockingServer.AsyncFrameBuffer fb, final int seqid) {
        final org.apache.thrift.AsyncProcessFunction fcall = this;
        return new org.apache.thrift.async.AsyncMethodCallback<Placar>() { 
          public void onComplete(Placar o) {
            exibir_rodada_result result = new exibir_rodada_result();
            result.success = o;
            try {
              fcall.sendResponse(fb, result, org.apache.thrift.protocol.TMessageType.REPLY,seqid);
            } catch (org.apache.thrift.transport.TTransportException e) {
              _LOGGER.error("TTransportException writing to internal frame buffer", e);
              fb.close();
            } catch (java.lang.Exception e) {
              _LOGGER.error("Exception writing to internal frame buffer", e);
              onError(e);
            }
          }
          public void onError(java.lang.Exception e) {
            byte msgType = org.apache.thrift.protocol.TMessageType.REPLY;
            org.apache.thrift.TSerializable msg;
            exibir_rodada_result result = new exibir_rodada_result();
            if (e instanceof org.apache.thrift.transport.TTransportException) {
              _LOGGER.error("TTransportException inside handler", e);
              fb.close();
              return;
            } else if (e instanceof org.apache.thrift.TApplicationException) {
              _LOGGER.error("TApplicationException inside handler", e);
              msgType = org.apache.thrift.protocol.TMessageType.EXCEPTION;
              msg = (org.apache.thrift.TApplicationException)e;
            } else {
              _LOGGER.error("Exception inside handler", e);
              msgType = org.apache.thrift.protocol.TMessageType.EXCEPTION;
              msg = new org.apache.thrift.TApplicationException(org.apache.thrift.TApplicationException.INTERNAL_ERROR, e.getMessage());
            }
            try {
              fcall.sendResponse(fb,msg,msgType,seqid);
            } catch (java.lang.Exception ex) {
              _LOGGER.error("Exception writing to internal frame buffer", ex);
              fb.close();
            }
          }
        };
      }

      protected boolean isOneway() {
        return false;
      }

      public void start(I iface, exibir_rodada_args args, org.apache.thrift.async.AsyncMethodCallback<Placar> resultHandler) throws org.apache.thrift.TException {
        iface.exibir_rodada(args.jogador,resultHandler);
      }
    }

  }

  public static class gerar_rodada_args implements org.apache.thrift.TBase<gerar_rodada_args, gerar_rodada_args._Fields>, java.io.Serializable, Cloneable, Comparable<gerar_rodada_args>   {
    private static final org.apache.thrift.protocol.TStruct STRUCT_DESC = new org.apache.thrift.protocol.TStruct("gerar_rodada_args");

    private static final org.apache.thrift.protocol.TField LETRA_FIELD_DESC = new org.apache.thrift.protocol.TField("letra", org.apache.thrift.protocol.TType.STRUCT, (short)1);
    private static final org.apache.thrift.protocol.TField JOGADOR_FIELD_DESC = new org.apache.thrift.protocol.TField("jogador", org.apache.thrift.protocol.TType.STRUCT, (short)2);

    private static final org.apache.thrift.scheme.SchemeFactory STANDARD_SCHEME_FACTORY = new gerar_rodada_argsStandardSchemeFactory();
    private static final org.apache.thrift.scheme.SchemeFactory TUPLE_SCHEME_FACTORY = new gerar_rodada_argsTupleSchemeFactory();

    public @org.apache.thrift.annotation.Nullable Letra letra; // required
    public @org.apache.thrift.annotation.Nullable idJogador jogador; // required

    /** The set of fields this struct contains, along with convenience methods for finding and manipulating them. */
    public enum _Fields implements org.apache.thrift.TFieldIdEnum {
      LETRA((short)1, "letra"),
      JOGADOR((short)2, "jogador");

      private static final java.util.Map<java.lang.String, _Fields> byName = new java.util.HashMap<java.lang.String, _Fields>();

      static {
        for (_Fields field : java.util.EnumSet.allOf(_Fields.class)) {
          byName.put(field.getFieldName(), field);
        }
      }

      /**
       * Find the _Fields constant that matches fieldId, or null if its not found.
       */
      @org.apache.thrift.annotation.Nullable
      public static _Fields findByThriftId(int fieldId) {
        switch(fieldId) {
          case 1: // LETRA
            return LETRA;
          case 2: // JOGADOR
            return JOGADOR;
          default:
            return null;
        }
      }

      /**
       * Find the _Fields constant that matches fieldId, throwing an exception
       * if it is not found.
       */
      public static _Fields findByThriftIdOrThrow(int fieldId) {
        _Fields fields = findByThriftId(fieldId);
        if (fields == null) throw new java.lang.IllegalArgumentException("Field " + fieldId + " doesn't exist!");
        return fields;
      }

      /**
       * Find the _Fields constant that matches name, or null if its not found.
       */
      @org.apache.thrift.annotation.Nullable
      public static _Fields findByName(java.lang.String name) {
        return byName.get(name);
      }

      private final short _thriftId;
      private final java.lang.String _fieldName;

      _Fields(short thriftId, java.lang.String fieldName) {
        _thriftId = thriftId;
        _fieldName = fieldName;
      }

      public short getThriftFieldId() {
        return _thriftId;
      }

      public java.lang.String getFieldName() {
        return _fieldName;
      }
    }

    // isset id assignments
    public static final java.util.Map<_Fields, org.apache.thrift.meta_data.FieldMetaData> metaDataMap;
    static {
      java.util.Map<_Fields, org.apache.thrift.meta_data.FieldMetaData> tmpMap = new java.util.EnumMap<_Fields, org.apache.thrift.meta_data.FieldMetaData>(_Fields.class);
      tmpMap.put(_Fields.LETRA, new org.apache.thrift.meta_data.FieldMetaData("letra", org.apache.thrift.TFieldRequirementType.DEFAULT, 
          new org.apache.thrift.meta_data.StructMetaData(org.apache.thrift.protocol.TType.STRUCT, Letra.class)));
      tmpMap.put(_Fields.JOGADOR, new org.apache.thrift.meta_data.FieldMetaData("jogador", org.apache.thrift.TFieldRequirementType.DEFAULT, 
          new org.apache.thrift.meta_data.StructMetaData(org.apache.thrift.protocol.TType.STRUCT, idJogador.class)));
      metaDataMap = java.util.Collections.unmodifiableMap(tmpMap);
      org.apache.thrift.meta_data.FieldMetaData.addStructMetaDataMap(gerar_rodada_args.class, metaDataMap);
    }

    public gerar_rodada_args() {
    }

    public gerar_rodada_args(
      Letra letra,
      idJogador jogador)
    {
      this();
      this.letra = letra;
      this.jogador = jogador;
    }

    /**
     * Performs a deep copy on <i>other</i>.
     */
    public gerar_rodada_args(gerar_rodada_args other) {
      if (other.isSetLetra()) {
        this.letra = new Letra(other.letra);
      }
      if (other.isSetJogador()) {
        this.jogador = new idJogador(other.jogador);
      }
    }

    public gerar_rodada_args deepCopy() {
      return new gerar_rodada_args(this);
    }

    @Override
    public void clear() {
      this.letra = null;
      this.jogador = null;
    }

    @org.apache.thrift.annotation.Nullable
    public Letra getLetra() {
      return this.letra;
    }

    public gerar_rodada_args setLetra(@org.apache.thrift.annotation.Nullable Letra letra) {
      this.letra = letra;
      return this;
    }

    public void unsetLetra() {
      this.letra = null;
    }

    /** Returns true if field letra is set (has been assigned a value) and false otherwise */
    public boolean isSetLetra() {
      return this.letra != null;
    }

    public void setLetraIsSet(boolean value) {
      if (!value) {
        this.letra = null;
      }
    }

    @org.apache.thrift.annotation.Nullable
    public idJogador getJogador() {
      return this.jogador;
    }

    public gerar_rodada_args setJogador(@org.apache.thrift.annotation.Nullable idJogador jogador) {
      this.jogador = jogador;
      return this;
    }

    public void unsetJogador() {
      this.jogador = null;
    }

    /** Returns true if field jogador is set (has been assigned a value) and false otherwise */
    public boolean isSetJogador() {
      return this.jogador != null;
    }

    public void setJogadorIsSet(boolean value) {
      if (!value) {
        this.jogador = null;
      }
    }

    public void setFieldValue(_Fields field, @org.apache.thrift.annotation.Nullable java.lang.Object value) {
      switch (field) {
      case LETRA:
        if (value == null) {
          unsetLetra();
        } else {
          setLetra((Letra)value);
        }
        break;

      case JOGADOR:
        if (value == null) {
          unsetJogador();
        } else {
          setJogador((idJogador)value);
        }
        break;

      }
    }

    @org.apache.thrift.annotation.Nullable
    public java.lang.Object getFieldValue(_Fields field) {
      switch (field) {
      case LETRA:
        return getLetra();

      case JOGADOR:
        return getJogador();

      }
      throw new java.lang.IllegalStateException();
    }

    /** Returns true if field corresponding to fieldID is set (has been assigned a value) and false otherwise */
    public boolean isSet(_Fields field) {
      if (field == null) {
        throw new java.lang.IllegalArgumentException();
      }

      switch (field) {
      case LETRA:
        return isSetLetra();
      case JOGADOR:
        return isSetJogador();
      }
      throw new java.lang.IllegalStateException();
    }

    @Override
    public boolean equals(java.lang.Object that) {
      if (that == null)
        return false;
      if (that instanceof gerar_rodada_args)
        return this.equals((gerar_rodada_args)that);
      return false;
    }

    public boolean equals(gerar_rodada_args that) {
      if (that == null)
        return false;
      if (this == that)
        return true;

      boolean this_present_letra = true && this.isSetLetra();
      boolean that_present_letra = true && that.isSetLetra();
      if (this_present_letra || that_present_letra) {
        if (!(this_present_letra && that_present_letra))
          return false;
        if (!this.letra.equals(that.letra))
          return false;
      }

      boolean this_present_jogador = true && this.isSetJogador();
      boolean that_present_jogador = true && that.isSetJogador();
      if (this_present_jogador || that_present_jogador) {
        if (!(this_present_jogador && that_present_jogador))
          return false;
        if (!this.jogador.equals(that.jogador))
          return false;
      }

      return true;
    }

    @Override
    public int hashCode() {
      int hashCode = 1;

      hashCode = hashCode * 8191 + ((isSetLetra()) ? 131071 : 524287);
      if (isSetLetra())
        hashCode = hashCode * 8191 + letra.hashCode();

      hashCode = hashCode * 8191 + ((isSetJogador()) ? 131071 : 524287);
      if (isSetJogador())
        hashCode = hashCode * 8191 + jogador.hashCode();

      return hashCode;
    }

    @Override
    public int compareTo(gerar_rodada_args other) {
      if (!getClass().equals(other.getClass())) {
        return getClass().getName().compareTo(other.getClass().getName());
      }

      int lastComparison = 0;

      lastComparison = java.lang.Boolean.valueOf(isSetLetra()).compareTo(other.isSetLetra());
      if (lastComparison != 0) {
        return lastComparison;
      }
      if (isSetLetra()) {
        lastComparison = org.apache.thrift.TBaseHelper.compareTo(this.letra, other.letra);
        if (lastComparison != 0) {
          return lastComparison;
        }
      }
      lastComparison = java.lang.Boolean.valueOf(isSetJogador()).compareTo(other.isSetJogador());
      if (lastComparison != 0) {
        return lastComparison;
      }
      if (isSetJogador()) {
        lastComparison = org.apache.thrift.TBaseHelper.compareTo(this.jogador, other.jogador);
        if (lastComparison != 0) {
          return lastComparison;
        }
      }
      return 0;
    }

    @org.apache.thrift.annotation.Nullable
    public _Fields fieldForId(int fieldId) {
      return _Fields.findByThriftId(fieldId);
    }

    public void read(org.apache.thrift.protocol.TProtocol iprot) throws org.apache.thrift.TException {
      scheme(iprot).read(iprot, this);
    }

    public void write(org.apache.thrift.protocol.TProtocol oprot) throws org.apache.thrift.TException {
      scheme(oprot).write(oprot, this);
    }

    @Override
    public java.lang.String toString() {
      java.lang.StringBuilder sb = new java.lang.StringBuilder("gerar_rodada_args(");
      boolean first = true;

      sb.append("letra:");
      if (this.letra == null) {
        sb.append("null");
      } else {
        sb.append(this.letra);
      }
      first = false;
      if (!first) sb.append(", ");
      sb.append("jogador:");
      if (this.jogador == null) {
        sb.append("null");
      } else {
        sb.append(this.jogador);
      }
      first = false;
      sb.append(")");
      return sb.toString();
    }

    public void validate() throws org.apache.thrift.TException {
      // check for required fields
      // check for sub-struct validity
      if (letra != null) {
        letra.validate();
      }
      if (jogador != null) {
        jogador.validate();
      }
    }

    private void writeObject(java.io.ObjectOutputStream out) throws java.io.IOException {
      try {
        write(new org.apache.thrift.protocol.TCompactProtocol(new org.apache.thrift.transport.TIOStreamTransport(out)));
      } catch (org.apache.thrift.TException te) {
        throw new java.io.IOException(te);
      }
    }

    private void readObject(java.io.ObjectInputStream in) throws java.io.IOException, java.lang.ClassNotFoundException {
      try {
        read(new org.apache.thrift.protocol.TCompactProtocol(new org.apache.thrift.transport.TIOStreamTransport(in)));
      } catch (org.apache.thrift.TException te) {
        throw new java.io.IOException(te);
      }
    }

    private static class gerar_rodada_argsStandardSchemeFactory implements org.apache.thrift.scheme.SchemeFactory {
      public gerar_rodada_argsStandardScheme getScheme() {
        return new gerar_rodada_argsStandardScheme();
      }
    }

    private static class gerar_rodada_argsStandardScheme extends org.apache.thrift.scheme.StandardScheme<gerar_rodada_args> {

      public void read(org.apache.thrift.protocol.TProtocol iprot, gerar_rodada_args struct) throws org.apache.thrift.TException {
        org.apache.thrift.protocol.TField schemeField;
        iprot.readStructBegin();
        while (true)
        {
          schemeField = iprot.readFieldBegin();
          if (schemeField.type == org.apache.thrift.protocol.TType.STOP) { 
            break;
          }
          switch (schemeField.id) {
            case 1: // LETRA
              if (schemeField.type == org.apache.thrift.protocol.TType.STRUCT) {
                struct.letra = new Letra();
                struct.letra.read(iprot);
                struct.setLetraIsSet(true);
              } else { 
                org.apache.thrift.protocol.TProtocolUtil.skip(iprot, schemeField.type);
              }
              break;
            case 2: // JOGADOR
              if (schemeField.type == org.apache.thrift.protocol.TType.STRUCT) {
                struct.jogador = new idJogador();
                struct.jogador.read(iprot);
                struct.setJogadorIsSet(true);
              } else { 
                org.apache.thrift.protocol.TProtocolUtil.skip(iprot, schemeField.type);
              }
              break;
            default:
              org.apache.thrift.protocol.TProtocolUtil.skip(iprot, schemeField.type);
          }
          iprot.readFieldEnd();
        }
        iprot.readStructEnd();

        // check for required fields of primitive type, which can't be checked in the validate method
        struct.validate();
      }

      public void write(org.apache.thrift.protocol.TProtocol oprot, gerar_rodada_args struct) throws org.apache.thrift.TException {
        struct.validate();

        oprot.writeStructBegin(STRUCT_DESC);
        if (struct.letra != null) {
          oprot.writeFieldBegin(LETRA_FIELD_DESC);
          struct.letra.write(oprot);
          oprot.writeFieldEnd();
        }
        if (struct.jogador != null) {
          oprot.writeFieldBegin(JOGADOR_FIELD_DESC);
          struct.jogador.write(oprot);
          oprot.writeFieldEnd();
        }
        oprot.writeFieldStop();
        oprot.writeStructEnd();
      }

    }

    private static class gerar_rodada_argsTupleSchemeFactory implements org.apache.thrift.scheme.SchemeFactory {
      public gerar_rodada_argsTupleScheme getScheme() {
        return new gerar_rodada_argsTupleScheme();
      }
    }

    private static class gerar_rodada_argsTupleScheme extends org.apache.thrift.scheme.TupleScheme<gerar_rodada_args> {

      @Override
      public void write(org.apache.thrift.protocol.TProtocol prot, gerar_rodada_args struct) throws org.apache.thrift.TException {
        org.apache.thrift.protocol.TTupleProtocol oprot = (org.apache.thrift.protocol.TTupleProtocol) prot;
        java.util.BitSet optionals = new java.util.BitSet();
        if (struct.isSetLetra()) {
          optionals.set(0);
        }
        if (struct.isSetJogador()) {
          optionals.set(1);
        }
        oprot.writeBitSet(optionals, 2);
        if (struct.isSetLetra()) {
          struct.letra.write(oprot);
        }
        if (struct.isSetJogador()) {
          struct.jogador.write(oprot);
        }
      }

      @Override
      public void read(org.apache.thrift.protocol.TProtocol prot, gerar_rodada_args struct) throws org.apache.thrift.TException {
        org.apache.thrift.protocol.TTupleProtocol iprot = (org.apache.thrift.protocol.TTupleProtocol) prot;
        java.util.BitSet incoming = iprot.readBitSet(2);
        if (incoming.get(0)) {
          struct.letra = new Letra();
          struct.letra.read(iprot);
          struct.setLetraIsSet(true);
        }
        if (incoming.get(1)) {
          struct.jogador = new idJogador();
          struct.jogador.read(iprot);
          struct.setJogadorIsSet(true);
        }
      }
    }

    private static <S extends org.apache.thrift.scheme.IScheme> S scheme(org.apache.thrift.protocol.TProtocol proto) {
      return (org.apache.thrift.scheme.StandardScheme.class.equals(proto.getScheme()) ? STANDARD_SCHEME_FACTORY : TUPLE_SCHEME_FACTORY).getScheme();
    }
  }

  public static class gerar_rodada_result implements org.apache.thrift.TBase<gerar_rodada_result, gerar_rodada_result._Fields>, java.io.Serializable, Cloneable, Comparable<gerar_rodada_result>   {
    private static final org.apache.thrift.protocol.TStruct STRUCT_DESC = new org.apache.thrift.protocol.TStruct("gerar_rodada_result");

    private static final org.apache.thrift.protocol.TField SUCCESS_FIELD_DESC = new org.apache.thrift.protocol.TField("success", org.apache.thrift.protocol.TType.STRUCT, (short)0);

    private static final org.apache.thrift.scheme.SchemeFactory STANDARD_SCHEME_FACTORY = new gerar_rodada_resultStandardSchemeFactory();
    private static final org.apache.thrift.scheme.SchemeFactory TUPLE_SCHEME_FACTORY = new gerar_rodada_resultTupleSchemeFactory();

    public @org.apache.thrift.annotation.Nullable Placar success; // required

    /** The set of fields this struct contains, along with convenience methods for finding and manipulating them. */
    public enum _Fields implements org.apache.thrift.TFieldIdEnum {
      SUCCESS((short)0, "success");

      private static final java.util.Map<java.lang.String, _Fields> byName = new java.util.HashMap<java.lang.String, _Fields>();

      static {
        for (_Fields field : java.util.EnumSet.allOf(_Fields.class)) {
          byName.put(field.getFieldName(), field);
        }
      }

      /**
       * Find the _Fields constant that matches fieldId, or null if its not found.
       */
      @org.apache.thrift.annotation.Nullable
      public static _Fields findByThriftId(int fieldId) {
        switch(fieldId) {
          case 0: // SUCCESS
            return SUCCESS;
          default:
            return null;
        }
      }

      /**
       * Find the _Fields constant that matches fieldId, throwing an exception
       * if it is not found.
       */
      public static _Fields findByThriftIdOrThrow(int fieldId) {
        _Fields fields = findByThriftId(fieldId);
        if (fields == null) throw new java.lang.IllegalArgumentException("Field " + fieldId + " doesn't exist!");
        return fields;
      }

      /**
       * Find the _Fields constant that matches name, or null if its not found.
       */
      @org.apache.thrift.annotation.Nullable
      public static _Fields findByName(java.lang.String name) {
        return byName.get(name);
      }

      private final short _thriftId;
      private final java.lang.String _fieldName;

      _Fields(short thriftId, java.lang.String fieldName) {
        _thriftId = thriftId;
        _fieldName = fieldName;
      }

      public short getThriftFieldId() {
        return _thriftId;
      }

      public java.lang.String getFieldName() {
        return _fieldName;
      }
    }

    // isset id assignments
    public static final java.util.Map<_Fields, org.apache.thrift.meta_data.FieldMetaData> metaDataMap;
    static {
      java.util.Map<_Fields, org.apache.thrift.meta_data.FieldMetaData> tmpMap = new java.util.EnumMap<_Fields, org.apache.thrift.meta_data.FieldMetaData>(_Fields.class);
      tmpMap.put(_Fields.SUCCESS, new org.apache.thrift.meta_data.FieldMetaData("success", org.apache.thrift.TFieldRequirementType.DEFAULT, 
          new org.apache.thrift.meta_data.StructMetaData(org.apache.thrift.protocol.TType.STRUCT, Placar.class)));
      metaDataMap = java.util.Collections.unmodifiableMap(tmpMap);
      org.apache.thrift.meta_data.FieldMetaData.addStructMetaDataMap(gerar_rodada_result.class, metaDataMap);
    }

    public gerar_rodada_result() {
    }

    public gerar_rodada_result(
      Placar success)
    {
      this();
      this.success = success;
    }

    /**
     * Performs a deep copy on <i>other</i>.
     */
    public gerar_rodada_result(gerar_rodada_result other) {
      if (other.isSetSuccess()) {
        this.success = new Placar(other.success);
      }
    }

    public gerar_rodada_result deepCopy() {
      return new gerar_rodada_result(this);
    }

    @Override
    public void clear() {
      this.success = null;
    }

    @org.apache.thrift.annotation.Nullable
    public Placar getSuccess() {
      return this.success;
    }

    public gerar_rodada_result setSuccess(@org.apache.thrift.annotation.Nullable Placar success) {
      this.success = success;
      return this;
    }

    public void unsetSuccess() {
      this.success = null;
    }

    /** Returns true if field success is set (has been assigned a value) and false otherwise */
    public boolean isSetSuccess() {
      return this.success != null;
    }

    public void setSuccessIsSet(boolean value) {
      if (!value) {
        this.success = null;
      }
    }

    public void setFieldValue(_Fields field, @org.apache.thrift.annotation.Nullable java.lang.Object value) {
      switch (field) {
      case SUCCESS:
        if (value == null) {
          unsetSuccess();
        } else {
          setSuccess((Placar)value);
        }
        break;

      }
    }

    @org.apache.thrift.annotation.Nullable
    public java.lang.Object getFieldValue(_Fields field) {
      switch (field) {
      case SUCCESS:
        return getSuccess();

      }
      throw new java.lang.IllegalStateException();
    }

    /** Returns true if field corresponding to fieldID is set (has been assigned a value) and false otherwise */
    public boolean isSet(_Fields field) {
      if (field == null) {
        throw new java.lang.IllegalArgumentException();
      }

      switch (field) {
      case SUCCESS:
        return isSetSuccess();
      }
      throw new java.lang.IllegalStateException();
    }

    @Override
    public boolean equals(java.lang.Object that) {
      if (that == null)
        return false;
      if (that instanceof gerar_rodada_result)
        return this.equals((gerar_rodada_result)that);
      return false;
    }

    public boolean equals(gerar_rodada_result that) {
      if (that == null)
        return false;
      if (this == that)
        return true;

      boolean this_present_success = true && this.isSetSuccess();
      boolean that_present_success = true && that.isSetSuccess();
      if (this_present_success || that_present_success) {
        if (!(this_present_success && that_present_success))
          return false;
        if (!this.success.equals(that.success))
          return false;
      }

      return true;
    }

    @Override
    public int hashCode() {
      int hashCode = 1;

      hashCode = hashCode * 8191 + ((isSetSuccess()) ? 131071 : 524287);
      if (isSetSuccess())
        hashCode = hashCode * 8191 + success.hashCode();

      return hashCode;
    }

    @Override
    public int compareTo(gerar_rodada_result other) {
      if (!getClass().equals(other.getClass())) {
        return getClass().getName().compareTo(other.getClass().getName());
      }

      int lastComparison = 0;

      lastComparison = java.lang.Boolean.valueOf(isSetSuccess()).compareTo(other.isSetSuccess());
      if (lastComparison != 0) {
        return lastComparison;
      }
      if (isSetSuccess()) {
        lastComparison = org.apache.thrift.TBaseHelper.compareTo(this.success, other.success);
        if (lastComparison != 0) {
          return lastComparison;
        }
      }
      return 0;
    }

    @org.apache.thrift.annotation.Nullable
    public _Fields fieldForId(int fieldId) {
      return _Fields.findByThriftId(fieldId);
    }

    public void read(org.apache.thrift.protocol.TProtocol iprot) throws org.apache.thrift.TException {
      scheme(iprot).read(iprot, this);
    }

    public void write(org.apache.thrift.protocol.TProtocol oprot) throws org.apache.thrift.TException {
      scheme(oprot).write(oprot, this);
      }

    @Override
    public java.lang.String toString() {
      java.lang.StringBuilder sb = new java.lang.StringBuilder("gerar_rodada_result(");
      boolean first = true;

      sb.append("success:");
      if (this.success == null) {
        sb.append("null");
      } else {
        sb.append(this.success);
      }
      first = false;
      sb.append(")");
      return sb.toString();
    }

    public void validate() throws org.apache.thrift.TException {
      // check for required fields
      // check for sub-struct validity
      if (success != null) {
        success.validate();
      }
    }

    private void writeObject(java.io.ObjectOutputStream out) throws java.io.IOException {
      try {
        write(new org.apache.thrift.protocol.TCompactProtocol(new org.apache.thrift.transport.TIOStreamTransport(out)));
      } catch (org.apache.thrift.TException te) {
        throw new java.io.IOException(te);
      }
    }

    private void readObject(java.io.ObjectInputStream in) throws java.io.IOException, java.lang.ClassNotFoundException {
      try {
        read(new org.apache.thrift.protocol.TCompactProtocol(new org.apache.thrift.transport.TIOStreamTransport(in)));
      } catch (org.apache.thrift.TException te) {
        throw new java.io.IOException(te);
      }
    }

    private static class gerar_rodada_resultStandardSchemeFactory implements org.apache.thrift.scheme.SchemeFactory {
      public gerar_rodada_resultStandardScheme getScheme() {
        return new gerar_rodada_resultStandardScheme();
      }
    }

    private static class gerar_rodada_resultStandardScheme extends org.apache.thrift.scheme.StandardScheme<gerar_rodada_result> {

      public void read(org.apache.thrift.protocol.TProtocol iprot, gerar_rodada_result struct) throws org.apache.thrift.TException {
        org.apache.thrift.protocol.TField schemeField;
        iprot.readStructBegin();
        while (true)
        {
          schemeField = iprot.readFieldBegin();
          if (schemeField.type == org.apache.thrift.protocol.TType.STOP) { 
            break;
          }
          switch (schemeField.id) {
            case 0: // SUCCESS
              if (schemeField.type == org.apache.thrift.protocol.TType.STRUCT) {
                struct.success = new Placar();
                struct.success.read(iprot);
                struct.setSuccessIsSet(true);
              } else { 
                org.apache.thrift.protocol.TProtocolUtil.skip(iprot, schemeField.type);
              }
              break;
            default:
              org.apache.thrift.protocol.TProtocolUtil.skip(iprot, schemeField.type);
          }
          iprot.readFieldEnd();
        }
        iprot.readStructEnd();

        // check for required fields of primitive type, which can't be checked in the validate method
        struct.validate();
      }

      public void write(org.apache.thrift.protocol.TProtocol oprot, gerar_rodada_result struct) throws org.apache.thrift.TException {
        struct.validate();

        oprot.writeStructBegin(STRUCT_DESC);
        if (struct.success != null) {
          oprot.writeFieldBegin(SUCCESS_FIELD_DESC);
          struct.success.write(oprot);
          oprot.writeFieldEnd();
        }
        oprot.writeFieldStop();
        oprot.writeStructEnd();
      }

    }

    private static class gerar_rodada_resultTupleSchemeFactory implements org.apache.thrift.scheme.SchemeFactory {
      public gerar_rodada_resultTupleScheme getScheme() {
        return new gerar_rodada_resultTupleScheme();
      }
    }

    private static class gerar_rodada_resultTupleScheme extends org.apache.thrift.scheme.TupleScheme<gerar_rodada_result> {

      @Override
      public void write(org.apache.thrift.protocol.TProtocol prot, gerar_rodada_result struct) throws org.apache.thrift.TException {
        org.apache.thrift.protocol.TTupleProtocol oprot = (org.apache.thrift.protocol.TTupleProtocol) prot;
        java.util.BitSet optionals = new java.util.BitSet();
        if (struct.isSetSuccess()) {
          optionals.set(0);
        }
        oprot.writeBitSet(optionals, 1);
        if (struct.isSetSuccess()) {
          struct.success.write(oprot);
        }
      }

      @Override
      public void read(org.apache.thrift.protocol.TProtocol prot, gerar_rodada_result struct) throws org.apache.thrift.TException {
        org.apache.thrift.protocol.TTupleProtocol iprot = (org.apache.thrift.protocol.TTupleProtocol) prot;
        java.util.BitSet incoming = iprot.readBitSet(1);
        if (incoming.get(0)) {
          struct.success = new Placar();
          struct.success.read(iprot);
          struct.setSuccessIsSet(true);
        }
      }
    }

    private static <S extends org.apache.thrift.scheme.IScheme> S scheme(org.apache.thrift.protocol.TProtocol proto) {
      return (org.apache.thrift.scheme.StandardScheme.class.equals(proto.getScheme()) ? STANDARD_SCHEME_FACTORY : TUPLE_SCHEME_FACTORY).getScheme();
    }
  }

  public static class exibir_rodada_args implements org.apache.thrift.TBase<exibir_rodada_args, exibir_rodada_args._Fields>, java.io.Serializable, Cloneable, Comparable<exibir_rodada_args>   {
    private static final org.apache.thrift.protocol.TStruct STRUCT_DESC = new org.apache.thrift.protocol.TStruct("exibir_rodada_args");

    private static final org.apache.thrift.protocol.TField JOGADOR_FIELD_DESC = new org.apache.thrift.protocol.TField("jogador", org.apache.thrift.protocol.TType.STRUCT, (short)1);

    private static final org.apache.thrift.scheme.SchemeFactory STANDARD_SCHEME_FACTORY = new exibir_rodada_argsStandardSchemeFactory();
    private static final org.apache.thrift.scheme.SchemeFactory TUPLE_SCHEME_FACTORY = new exibir_rodada_argsTupleSchemeFactory();

    public @org.apache.thrift.annotation.Nullable idJogador jogador; // required

    /** The set of fields this struct contains, along with convenience methods for finding and manipulating them. */
    public enum _Fields implements org.apache.thrift.TFieldIdEnum {
      JOGADOR((short)1, "jogador");

      private static final java.util.Map<java.lang.String, _Fields> byName = new java.util.HashMap<java.lang.String, _Fields>();

      static {
        for (_Fields field : java.util.EnumSet.allOf(_Fields.class)) {
          byName.put(field.getFieldName(), field);
        }
      }

      /**
       * Find the _Fields constant that matches fieldId, or null if its not found.
       */
      @org.apache.thrift.annotation.Nullable
      public static _Fields findByThriftId(int fieldId) {
        switch(fieldId) {
          case 1: // JOGADOR
            return JOGADOR;
          default:
            return null;
        }
      }

      /**
       * Find the _Fields constant that matches fieldId, throwing an exception
       * if it is not found.
       */
      public static _Fields findByThriftIdOrThrow(int fieldId) {
        _Fields fields = findByThriftId(fieldId);
        if (fields == null) throw new java.lang.IllegalArgumentException("Field " + fieldId + " doesn't exist!");
        return fields;
      }

      /**
       * Find the _Fields constant that matches name, or null if its not found.
       */
      @org.apache.thrift.annotation.Nullable
      public static _Fields findByName(java.lang.String name) {
        return byName.get(name);
      }

      private final short _thriftId;
      private final java.lang.String _fieldName;

      _Fields(short thriftId, java.lang.String fieldName) {
        _thriftId = thriftId;
        _fieldName = fieldName;
      }

      public short getThriftFieldId() {
        return _thriftId;
      }

      public java.lang.String getFieldName() {
        return _fieldName;
      }
    }

    // isset id assignments
    public static final java.util.Map<_Fields, org.apache.thrift.meta_data.FieldMetaData> metaDataMap;
    static {
      java.util.Map<_Fields, org.apache.thrift.meta_data.FieldMetaData> tmpMap = new java.util.EnumMap<_Fields, org.apache.thrift.meta_data.FieldMetaData>(_Fields.class);
      tmpMap.put(_Fields.JOGADOR, new org.apache.thrift.meta_data.FieldMetaData("jogador", org.apache.thrift.TFieldRequirementType.DEFAULT, 
          new org.apache.thrift.meta_data.StructMetaData(org.apache.thrift.protocol.TType.STRUCT, idJogador.class)));
      metaDataMap = java.util.Collections.unmodifiableMap(tmpMap);
      org.apache.thrift.meta_data.FieldMetaData.addStructMetaDataMap(exibir_rodada_args.class, metaDataMap);
    }

    public exibir_rodada_args() {
    }

    public exibir_rodada_args(
      idJogador jogador)
    {
      this();
      this.jogador = jogador;
    }

    /**
     * Performs a deep copy on <i>other</i>.
     */
    public exibir_rodada_args(exibir_rodada_args other) {
      if (other.isSetJogador()) {
        this.jogador = new idJogador(other.jogador);
      }
    }

    public exibir_rodada_args deepCopy() {
      return new exibir_rodada_args(this);
    }

    @Override
    public void clear() {
      this.jogador = null;
    }

    @org.apache.thrift.annotation.Nullable
    public idJogador getJogador() {
      return this.jogador;
    }

    public exibir_rodada_args setJogador(@org.apache.thrift.annotation.Nullable idJogador jogador) {
      this.jogador = jogador;
      return this;
    }

    public void unsetJogador() {
      this.jogador = null;
    }

    /** Returns true if field jogador is set (has been assigned a value) and false otherwise */
    public boolean isSetJogador() {
      return this.jogador != null;
    }

    public void setJogadorIsSet(boolean value) {
      if (!value) {
        this.jogador = null;
      }
    }

    public void setFieldValue(_Fields field, @org.apache.thrift.annotation.Nullable java.lang.Object value) {
      switch (field) {
      case JOGADOR:
        if (value == null) {
          unsetJogador();
        } else {
          setJogador((idJogador)value);
        }
        break;

      }
    }

    @org.apache.thrift.annotation.Nullable
    public java.lang.Object getFieldValue(_Fields field) {
      switch (field) {
      case JOGADOR:
        return getJogador();

      }
      throw new java.lang.IllegalStateException();
    }

    /** Returns true if field corresponding to fieldID is set (has been assigned a value) and false otherwise */
    public boolean isSet(_Fields field) {
      if (field == null) {
        throw new java.lang.IllegalArgumentException();
      }

      switch (field) {
      case JOGADOR:
        return isSetJogador();
      }
      throw new java.lang.IllegalStateException();
    }

    @Override
    public boolean equals(java.lang.Object that) {
      if (that == null)
        return false;
      if (that instanceof exibir_rodada_args)
        return this.equals((exibir_rodada_args)that);
      return false;
    }

    public boolean equals(exibir_rodada_args that) {
      if (that == null)
        return false;
      if (this == that)
        return true;

      boolean this_present_jogador = true && this.isSetJogador();
      boolean that_present_jogador = true && that.isSetJogador();
      if (this_present_jogador || that_present_jogador) {
        if (!(this_present_jogador && that_present_jogador))
          return false;
        if (!this.jogador.equals(that.jogador))
          return false;
      }

      return true;
    }

    @Override
    public int hashCode() {
      int hashCode = 1;

      hashCode = hashCode * 8191 + ((isSetJogador()) ? 131071 : 524287);
      if (isSetJogador())
        hashCode = hashCode * 8191 + jogador.hashCode();

      return hashCode;
    }

    @Override
    public int compareTo(exibir_rodada_args other) {
      if (!getClass().equals(other.getClass())) {
        return getClass().getName().compareTo(other.getClass().getName());
      }

      int lastComparison = 0;

      lastComparison = java.lang.Boolean.valueOf(isSetJogador()).compareTo(other.isSetJogador());
      if (lastComparison != 0) {
        return lastComparison;
      }
      if (isSetJogador()) {
        lastComparison = org.apache.thrift.TBaseHelper.compareTo(this.jogador, other.jogador);
        if (lastComparison != 0) {
          return lastComparison;
        }
      }
      return 0;
    }

    @org.apache.thrift.annotation.Nullable
    public _Fields fieldForId(int fieldId) {
      return _Fields.findByThriftId(fieldId);
    }

    public void read(org.apache.thrift.protocol.TProtocol iprot) throws org.apache.thrift.TException {
      scheme(iprot).read(iprot, this);
    }

    public void write(org.apache.thrift.protocol.TProtocol oprot) throws org.apache.thrift.TException {
      scheme(oprot).write(oprot, this);
    }

    @Override
    public java.lang.String toString() {
      java.lang.StringBuilder sb = new java.lang.StringBuilder("exibir_rodada_args(");
      boolean first = true;

      sb.append("jogador:");
      if (this.jogador == null) {
        sb.append("null");
      } else {
        sb.append(this.jogador);
      }
      first = false;
      sb.append(")");
      return sb.toString();
    }

    public void validate() throws org.apache.thrift.TException {
      // check for required fields
      // check for sub-struct validity
      if (jogador != null) {
        jogador.validate();
      }
    }

    private void writeObject(java.io.ObjectOutputStream out) throws java.io.IOException {
      try {
        write(new org.apache.thrift.protocol.TCompactProtocol(new org.apache.thrift.transport.TIOStreamTransport(out)));
      } catch (org.apache.thrift.TException te) {
        throw new java.io.IOException(te);
      }
    }

    private void readObject(java.io.ObjectInputStream in) throws java.io.IOException, java.lang.ClassNotFoundException {
      try {
        read(new org.apache.thrift.protocol.TCompactProtocol(new org.apache.thrift.transport.TIOStreamTransport(in)));
      } catch (org.apache.thrift.TException te) {
        throw new java.io.IOException(te);
      }
    }

    private static class exibir_rodada_argsStandardSchemeFactory implements org.apache.thrift.scheme.SchemeFactory {
      public exibir_rodada_argsStandardScheme getScheme() {
        return new exibir_rodada_argsStandardScheme();
      }
    }

    private static class exibir_rodada_argsStandardScheme extends org.apache.thrift.scheme.StandardScheme<exibir_rodada_args> {

      public void read(org.apache.thrift.protocol.TProtocol iprot, exibir_rodada_args struct) throws org.apache.thrift.TException {
        org.apache.thrift.protocol.TField schemeField;
        iprot.readStructBegin();
        while (true)
        {
          schemeField = iprot.readFieldBegin();
          if (schemeField.type == org.apache.thrift.protocol.TType.STOP) { 
            break;
          }
          switch (schemeField.id) {
            case 1: // JOGADOR
              if (schemeField.type == org.apache.thrift.protocol.TType.STRUCT) {
                struct.jogador = new idJogador();
                struct.jogador.read(iprot);
                struct.setJogadorIsSet(true);
              } else { 
                org.apache.thrift.protocol.TProtocolUtil.skip(iprot, schemeField.type);
              }
              break;
            default:
              org.apache.thrift.protocol.TProtocolUtil.skip(iprot, schemeField.type);
          }
          iprot.readFieldEnd();
        }
        iprot.readStructEnd();

        // check for required fields of primitive type, which can't be checked in the validate method
        struct.validate();
      }

      public void write(org.apache.thrift.protocol.TProtocol oprot, exibir_rodada_args struct) throws org.apache.thrift.TException {
        struct.validate();

        oprot.writeStructBegin(STRUCT_DESC);
        if (struct.jogador != null) {
          oprot.writeFieldBegin(JOGADOR_FIELD_DESC);
          struct.jogador.write(oprot);
          oprot.writeFieldEnd();
        }
        oprot.writeFieldStop();
        oprot.writeStructEnd();
      }

    }

    private static class exibir_rodada_argsTupleSchemeFactory implements org.apache.thrift.scheme.SchemeFactory {
      public exibir_rodada_argsTupleScheme getScheme() {
        return new exibir_rodada_argsTupleScheme();
      }
    }

    private static class exibir_rodada_argsTupleScheme extends org.apache.thrift.scheme.TupleScheme<exibir_rodada_args> {

      @Override
      public void write(org.apache.thrift.protocol.TProtocol prot, exibir_rodada_args struct) throws org.apache.thrift.TException {
        org.apache.thrift.protocol.TTupleProtocol oprot = (org.apache.thrift.protocol.TTupleProtocol) prot;
        java.util.BitSet optionals = new java.util.BitSet();
        if (struct.isSetJogador()) {
          optionals.set(0);
        }
        oprot.writeBitSet(optionals, 1);
        if (struct.isSetJogador()) {
          struct.jogador.write(oprot);
        }
      }

      @Override
      public void read(org.apache.thrift.protocol.TProtocol prot, exibir_rodada_args struct) throws org.apache.thrift.TException {
        org.apache.thrift.protocol.TTupleProtocol iprot = (org.apache.thrift.protocol.TTupleProtocol) prot;
        java.util.BitSet incoming = iprot.readBitSet(1);
        if (incoming.get(0)) {
          struct.jogador = new idJogador();
          struct.jogador.read(iprot);
          struct.setJogadorIsSet(true);
        }
      }
    }

    private static <S extends org.apache.thrift.scheme.IScheme> S scheme(org.apache.thrift.protocol.TProtocol proto) {
      return (org.apache.thrift.scheme.StandardScheme.class.equals(proto.getScheme()) ? STANDARD_SCHEME_FACTORY : TUPLE_SCHEME_FACTORY).getScheme();
    }
  }

  public static class exibir_rodada_result implements org.apache.thrift.TBase<exibir_rodada_result, exibir_rodada_result._Fields>, java.io.Serializable, Cloneable, Comparable<exibir_rodada_result>   {
    private static final org.apache.thrift.protocol.TStruct STRUCT_DESC = new org.apache.thrift.protocol.TStruct("exibir_rodada_result");

    private static final org.apache.thrift.protocol.TField SUCCESS_FIELD_DESC = new org.apache.thrift.protocol.TField("success", org.apache.thrift.protocol.TType.STRUCT, (short)0);

    private static final org.apache.thrift.scheme.SchemeFactory STANDARD_SCHEME_FACTORY = new exibir_rodada_resultStandardSchemeFactory();
    private static final org.apache.thrift.scheme.SchemeFactory TUPLE_SCHEME_FACTORY = new exibir_rodada_resultTupleSchemeFactory();

    public @org.apache.thrift.annotation.Nullable Placar success; // required

    /** The set of fields this struct contains, along with convenience methods for finding and manipulating them. */
    public enum _Fields implements org.apache.thrift.TFieldIdEnum {
      SUCCESS((short)0, "success");

      private static final java.util.Map<java.lang.String, _Fields> byName = new java.util.HashMap<java.lang.String, _Fields>();

      static {
        for (_Fields field : java.util.EnumSet.allOf(_Fields.class)) {
          byName.put(field.getFieldName(), field);
        }
      }

      /**
       * Find the _Fields constant that matches fieldId, or null if its not found.
       */
      @org.apache.thrift.annotation.Nullable
      public static _Fields findByThriftId(int fieldId) {
        switch(fieldId) {
          case 0: // SUCCESS
            return SUCCESS;
          default:
            return null;
        }
      }

      /**
       * Find the _Fields constant that matches fieldId, throwing an exception
       * if it is not found.
       */
      public static _Fields findByThriftIdOrThrow(int fieldId) {
        _Fields fields = findByThriftId(fieldId);
        if (fields == null) throw new java.lang.IllegalArgumentException("Field " + fieldId + " doesn't exist!");
        return fields;
      }

      /**
       * Find the _Fields constant that matches name, or null if its not found.
       */
      @org.apache.thrift.annotation.Nullable
      public static _Fields findByName(java.lang.String name) {
        return byName.get(name);
      }

      private final short _thriftId;
      private final java.lang.String _fieldName;

      _Fields(short thriftId, java.lang.String fieldName) {
        _thriftId = thriftId;
        _fieldName = fieldName;
      }

      public short getThriftFieldId() {
        return _thriftId;
      }

      public java.lang.String getFieldName() {
        return _fieldName;
      }
    }

    // isset id assignments
    public static final java.util.Map<_Fields, org.apache.thrift.meta_data.FieldMetaData> metaDataMap;
    static {
      java.util.Map<_Fields, org.apache.thrift.meta_data.FieldMetaData> tmpMap = new java.util.EnumMap<_Fields, org.apache.thrift.meta_data.FieldMetaData>(_Fields.class);
      tmpMap.put(_Fields.SUCCESS, new org.apache.thrift.meta_data.FieldMetaData("success", org.apache.thrift.TFieldRequirementType.DEFAULT, 
          new org.apache.thrift.meta_data.StructMetaData(org.apache.thrift.protocol.TType.STRUCT, Placar.class)));
      metaDataMap = java.util.Collections.unmodifiableMap(tmpMap);
      org.apache.thrift.meta_data.FieldMetaData.addStructMetaDataMap(exibir_rodada_result.class, metaDataMap);
    }

    public exibir_rodada_result() {
    }

    public exibir_rodada_result(
      Placar success)
    {
      this();
      this.success = success;
    }

    /**
     * Performs a deep copy on <i>other</i>.
     */
    public exibir_rodada_result(exibir_rodada_result other) {
      if (other.isSetSuccess()) {
        this.success = new Placar(other.success);
      }
    }

    public exibir_rodada_result deepCopy() {
      return new exibir_rodada_result(this);
    }

    @Override
    public void clear() {
      this.success = null;
    }

    @org.apache.thrift.annotation.Nullable
    public Placar getSuccess() {
      return this.success;
    }

    public exibir_rodada_result setSuccess(@org.apache.thrift.annotation.Nullable Placar success) {
      this.success = success;
      return this;
    }

    public void unsetSuccess() {
      this.success = null;
    }

    /** Returns true if field success is set (has been assigned a value) and false otherwise */
    public boolean isSetSuccess() {
      return this.success != null;
    }

    public void setSuccessIsSet(boolean value) {
      if (!value) {
        this.success = null;
      }
    }

    public void setFieldValue(_Fields field, @org.apache.thrift.annotation.Nullable java.lang.Object value) {
      switch (field) {
      case SUCCESS:
        if (value == null) {
          unsetSuccess();
        } else {
          setSuccess((Placar)value);
        }
        break;

      }
    }

    @org.apache.thrift.annotation.Nullable
    public java.lang.Object getFieldValue(_Fields field) {
      switch (field) {
      case SUCCESS:
        return getSuccess();

      }
      throw new java.lang.IllegalStateException();
    }

    /** Returns true if field corresponding to fieldID is set (has been assigned a value) and false otherwise */
    public boolean isSet(_Fields field) {
      if (field == null) {
        throw new java.lang.IllegalArgumentException();
      }

      switch (field) {
      case SUCCESS:
        return isSetSuccess();
      }
      throw new java.lang.IllegalStateException();
    }

    @Override
    public boolean equals(java.lang.Object that) {
      if (that == null)
        return false;
      if (that instanceof exibir_rodada_result)
        return this.equals((exibir_rodada_result)that);
      return false;
    }

    public boolean equals(exibir_rodada_result that) {
      if (that == null)
        return false;
      if (this == that)
        return true;

      boolean this_present_success = true && this.isSetSuccess();
      boolean that_present_success = true && that.isSetSuccess();
      if (this_present_success || that_present_success) {
        if (!(this_present_success && that_present_success))
          return false;
        if (!this.success.equals(that.success))
          return false;
      }

      return true;
    }

    @Override
    public int hashCode() {
      int hashCode = 1;

      hashCode = hashCode * 8191 + ((isSetSuccess()) ? 131071 : 524287);
      if (isSetSuccess())
        hashCode = hashCode * 8191 + success.hashCode();

      return hashCode;
    }

    @Override
    public int compareTo(exibir_rodada_result other) {
      if (!getClass().equals(other.getClass())) {
        return getClass().getName().compareTo(other.getClass().getName());
      }

      int lastComparison = 0;

      lastComparison = java.lang.Boolean.valueOf(isSetSuccess()).compareTo(other.isSetSuccess());
      if (lastComparison != 0) {
        return lastComparison;
      }
      if (isSetSuccess()) {
        lastComparison = org.apache.thrift.TBaseHelper.compareTo(this.success, other.success);
        if (lastComparison != 0) {
          return lastComparison;
        }
      }
      return 0;
    }

    @org.apache.thrift.annotation.Nullable
    public _Fields fieldForId(int fieldId) {
      return _Fields.findByThriftId(fieldId);
    }

    public void read(org.apache.thrift.protocol.TProtocol iprot) throws org.apache.thrift.TException {
      scheme(iprot).read(iprot, this);
    }

    public void write(org.apache.thrift.protocol.TProtocol oprot) throws org.apache.thrift.TException {
      scheme(oprot).write(oprot, this);
      }

    @Override
    public java.lang.String toString() {
      java.lang.StringBuilder sb = new java.lang.StringBuilder("exibir_rodada_result(");
      boolean first = true;

      sb.append("success:");
      if (this.success == null) {
        sb.append("null");
      } else {
        sb.append(this.success);
      }
      first = false;
      sb.append(")");
      return sb.toString();
    }

    public void validate() throws org.apache.thrift.TException {
      // check for required fields
      // check for sub-struct validity
      if (success != null) {
        success.validate();
      }
    }

    private void writeObject(java.io.ObjectOutputStream out) throws java.io.IOException {
      try {
        write(new org.apache.thrift.protocol.TCompactProtocol(new org.apache.thrift.transport.TIOStreamTransport(out)));
      } catch (org.apache.thrift.TException te) {
        throw new java.io.IOException(te);
      }
    }

    private void readObject(java.io.ObjectInputStream in) throws java.io.IOException, java.lang.ClassNotFoundException {
      try {
        read(new org.apache.thrift.protocol.TCompactProtocol(new org.apache.thrift.transport.TIOStreamTransport(in)));
      } catch (org.apache.thrift.TException te) {
        throw new java.io.IOException(te);
      }
    }

    private static class exibir_rodada_resultStandardSchemeFactory implements org.apache.thrift.scheme.SchemeFactory {
      public exibir_rodada_resultStandardScheme getScheme() {
        return new exibir_rodada_resultStandardScheme();
      }
    }

    private static class exibir_rodada_resultStandardScheme extends org.apache.thrift.scheme.StandardScheme<exibir_rodada_result> {

      public void read(org.apache.thrift.protocol.TProtocol iprot, exibir_rodada_result struct) throws org.apache.thrift.TException {
        org.apache.thrift.protocol.TField schemeField;
        iprot.readStructBegin();
        while (true)
        {
          schemeField = iprot.readFieldBegin();
          if (schemeField.type == org.apache.thrift.protocol.TType.STOP) { 
            break;
          }
          switch (schemeField.id) {
            case 0: // SUCCESS
              if (schemeField.type == org.apache.thrift.protocol.TType.STRUCT) {
                struct.success = new Placar();
                struct.success.read(iprot);
                struct.setSuccessIsSet(true);
              } else { 
                org.apache.thrift.protocol.TProtocolUtil.skip(iprot, schemeField.type);
              }
              break;
            default:
              org.apache.thrift.protocol.TProtocolUtil.skip(iprot, schemeField.type);
          }
          iprot.readFieldEnd();
        }
        iprot.readStructEnd();

        // check for required fields of primitive type, which can't be checked in the validate method
        struct.validate();
      }

      public void write(org.apache.thrift.protocol.TProtocol oprot, exibir_rodada_result struct) throws org.apache.thrift.TException {
        struct.validate();

        oprot.writeStructBegin(STRUCT_DESC);
        if (struct.success != null) {
          oprot.writeFieldBegin(SUCCESS_FIELD_DESC);
          struct.success.write(oprot);
          oprot.writeFieldEnd();
        }
        oprot.writeFieldStop();
        oprot.writeStructEnd();
      }

    }

    private static class exibir_rodada_resultTupleSchemeFactory implements org.apache.thrift.scheme.SchemeFactory {
      public exibir_rodada_resultTupleScheme getScheme() {
        return new exibir_rodada_resultTupleScheme();
      }
    }

    private static class exibir_rodada_resultTupleScheme extends org.apache.thrift.scheme.TupleScheme<exibir_rodada_result> {

      @Override
      public void write(org.apache.thrift.protocol.TProtocol prot, exibir_rodada_result struct) throws org.apache.thrift.TException {
        org.apache.thrift.protocol.TTupleProtocol oprot = (org.apache.thrift.protocol.TTupleProtocol) prot;
        java.util.BitSet optionals = new java.util.BitSet();
        if (struct.isSetSuccess()) {
          optionals.set(0);
        }
        oprot.writeBitSet(optionals, 1);
        if (struct.isSetSuccess()) {
          struct.success.write(oprot);
        }
      }

      @Override
      public void read(org.apache.thrift.protocol.TProtocol prot, exibir_rodada_result struct) throws org.apache.thrift.TException {
        org.apache.thrift.protocol.TTupleProtocol iprot = (org.apache.thrift.protocol.TTupleProtocol) prot;
        java.util.BitSet incoming = iprot.readBitSet(1);
        if (incoming.get(0)) {
          struct.success = new Placar();
          struct.success.read(iprot);
          struct.setSuccessIsSet(true);
        }
      }
    }

    private static <S extends org.apache.thrift.scheme.IScheme> S scheme(org.apache.thrift.protocol.TProtocol proto) {
      return (org.apache.thrift.scheme.StandardScheme.class.equals(proto.getScheme()) ? STANDARD_SCHEME_FACTORY : TUPLE_SCHEME_FACTORY).getScheme();
    }
  }

}
