/**
 * Autogenerated by Thrift Compiler (0.13.0)
 *
 * DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
 *  @generated
 */

@SuppressWarnings({"cast", "rawtypes", "serial", "unchecked", "unused"})
@javax.annotation.Generated(value = "Autogenerated by Thrift Compiler (0.13.0)", date = "2020-06-21")
public class Placar implements org.apache.thrift.TBase<Placar, Placar._Fields>, java.io.Serializable, Cloneable, Comparable<Placar> {
  private static final org.apache.thrift.protocol.TStruct STRUCT_DESC = new org.apache.thrift.protocol.TStruct("Placar");

  private static final org.apache.thrift.protocol.TField PLACAR_FIELD_DESC = new org.apache.thrift.protocol.TField("placar", org.apache.thrift.protocol.TType.STRING, (short)1);

  private static final org.apache.thrift.scheme.SchemeFactory STANDARD_SCHEME_FACTORY = new PlacarStandardSchemeFactory();
  private static final org.apache.thrift.scheme.SchemeFactory TUPLE_SCHEME_FACTORY = new PlacarTupleSchemeFactory();

  public @org.apache.thrift.annotation.Nullable java.lang.String placar; // required

  /** The set of fields this struct contains, along with convenience methods for finding and manipulating them. */
  public enum _Fields implements org.apache.thrift.TFieldIdEnum {
    PLACAR((short)1, "placar");

    private static final java.util.Map<java.lang.String, _Fields> byName = new java.util.HashMap<java.lang.String, _Fields>();

    static {
      for (_Fields field : java.util.EnumSet.allOf(_Fields.class)) {
        byName.put(field.getFieldName(), field);
      }
    }

    /**
     * Find the _Fields constant that matches fieldId, or null if its not found.
     */
    @org.apache.thrift.annotation.Nullable
    public static _Fields findByThriftId(int fieldId) {
      switch(fieldId) {
        case 1: // PLACAR
          return PLACAR;
        default:
          return null;
      }
    }

    /**
     * Find the _Fields constant that matches fieldId, throwing an exception
     * if it is not found.
     */
    public static _Fields findByThriftIdOrThrow(int fieldId) {
      _Fields fields = findByThriftId(fieldId);
      if (fields == null) throw new java.lang.IllegalArgumentException("Field " + fieldId + " doesn't exist!");
      return fields;
    }

    /**
     * Find the _Fields constant that matches name, or null if its not found.
     */
    @org.apache.thrift.annotation.Nullable
    public static _Fields findByName(java.lang.String name) {
      return byName.get(name);
    }

    private final short _thriftId;
    private final java.lang.String _fieldName;

    _Fields(short thriftId, java.lang.String fieldName) {
      _thriftId = thriftId;
      _fieldName = fieldName;
    }

    public short getThriftFieldId() {
      return _thriftId;
    }

    public java.lang.String getFieldName() {
      return _fieldName;
    }
  }

  // isset id assignments
  public static final java.util.Map<_Fields, org.apache.thrift.meta_data.FieldMetaData> metaDataMap;
  static {
    java.util.Map<_Fields, org.apache.thrift.meta_data.FieldMetaData> tmpMap = new java.util.EnumMap<_Fields, org.apache.thrift.meta_data.FieldMetaData>(_Fields.class);
    tmpMap.put(_Fields.PLACAR, new org.apache.thrift.meta_data.FieldMetaData("placar", org.apache.thrift.TFieldRequirementType.REQUIRED, 
        new org.apache.thrift.meta_data.FieldValueMetaData(org.apache.thrift.protocol.TType.STRING)));
    metaDataMap = java.util.Collections.unmodifiableMap(tmpMap);
    org.apache.thrift.meta_data.FieldMetaData.addStructMetaDataMap(Placar.class, metaDataMap);
  }

  public Placar() {
  }

  public Placar(
    java.lang.String placar)
  {
    this();
    this.placar = placar;
  }

  /**
   * Performs a deep copy on <i>other</i>.
   */
  public Placar(Placar other) {
    if (other.isSetPlacar()) {
      this.placar = other.placar;
    }
  }

  public Placar deepCopy() {
    return new Placar(this);
  }

  @Override
  public void clear() {
    this.placar = null;
  }

  @org.apache.thrift.annotation.Nullable
  public java.lang.String getPlacar() {
    return this.placar;
  }

  public Placar setPlacar(@org.apache.thrift.annotation.Nullable java.lang.String placar) {
    this.placar = placar;
    return this;
  }

  public void unsetPlacar() {
    this.placar = null;
  }

  /** Returns true if field placar is set (has been assigned a value) and false otherwise */
  public boolean isSetPlacar() {
    return this.placar != null;
  }

  public void setPlacarIsSet(boolean value) {
    if (!value) {
      this.placar = null;
    }
  }

  public void setFieldValue(_Fields field, @org.apache.thrift.annotation.Nullable java.lang.Object value) {
    switch (field) {
    case PLACAR:
      if (value == null) {
        unsetPlacar();
      } else {
        setPlacar((java.lang.String)value);
      }
      break;

    }
  }

  @org.apache.thrift.annotation.Nullable
  public java.lang.Object getFieldValue(_Fields field) {
    switch (field) {
    case PLACAR:
      return getPlacar();

    }
    throw new java.lang.IllegalStateException();
  }

  /** Returns true if field corresponding to fieldID is set (has been assigned a value) and false otherwise */
  public boolean isSet(_Fields field) {
    if (field == null) {
      throw new java.lang.IllegalArgumentException();
    }

    switch (field) {
    case PLACAR:
      return isSetPlacar();
    }
    throw new java.lang.IllegalStateException();
  }

  @Override
  public boolean equals(java.lang.Object that) {
    if (that == null)
      return false;
    if (that instanceof Placar)
      return this.equals((Placar)that);
    return false;
  }

  public boolean equals(Placar that) {
    if (that == null)
      return false;
    if (this == that)
      return true;

    boolean this_present_placar = true && this.isSetPlacar();
    boolean that_present_placar = true && that.isSetPlacar();
    if (this_present_placar || that_present_placar) {
      if (!(this_present_placar && that_present_placar))
        return false;
      if (!this.placar.equals(that.placar))
        return false;
    }

    return true;
  }

  @Override
  public int hashCode() {
    int hashCode = 1;

    hashCode = hashCode * 8191 + ((isSetPlacar()) ? 131071 : 524287);
    if (isSetPlacar())
      hashCode = hashCode * 8191 + placar.hashCode();

    return hashCode;
  }

  @Override
  public int compareTo(Placar other) {
    if (!getClass().equals(other.getClass())) {
      return getClass().getName().compareTo(other.getClass().getName());
    }

    int lastComparison = 0;

    lastComparison = java.lang.Boolean.valueOf(isSetPlacar()).compareTo(other.isSetPlacar());
    if (lastComparison != 0) {
      return lastComparison;
    }
    if (isSetPlacar()) {
      lastComparison = org.apache.thrift.TBaseHelper.compareTo(this.placar, other.placar);
      if (lastComparison != 0) {
        return lastComparison;
      }
    }
    return 0;
  }

  @org.apache.thrift.annotation.Nullable
  public _Fields fieldForId(int fieldId) {
    return _Fields.findByThriftId(fieldId);
  }

  public void read(org.apache.thrift.protocol.TProtocol iprot) throws org.apache.thrift.TException {
    scheme(iprot).read(iprot, this);
  }

  public void write(org.apache.thrift.protocol.TProtocol oprot) throws org.apache.thrift.TException {
    scheme(oprot).write(oprot, this);
  }

  @Override
  public java.lang.String toString() {
    java.lang.StringBuilder sb = new java.lang.StringBuilder("Placar(");
    boolean first = true;

    sb.append("placar:");
    if (this.placar == null) {
      sb.append("null");
    } else {
      sb.append(this.placar);
    }
    first = false;
    sb.append(")");
    return sb.toString();
  }

  public void validate() throws org.apache.thrift.TException {
    // check for required fields
    if (placar == null) {
      throw new org.apache.thrift.protocol.TProtocolException("Required field 'placar' was not present! Struct: " + toString());
    }
    // check for sub-struct validity
  }

  private void writeObject(java.io.ObjectOutputStream out) throws java.io.IOException {
    try {
      write(new org.apache.thrift.protocol.TCompactProtocol(new org.apache.thrift.transport.TIOStreamTransport(out)));
    } catch (org.apache.thrift.TException te) {
      throw new java.io.IOException(te);
    }
  }

  private void readObject(java.io.ObjectInputStream in) throws java.io.IOException, java.lang.ClassNotFoundException {
    try {
      read(new org.apache.thrift.protocol.TCompactProtocol(new org.apache.thrift.transport.TIOStreamTransport(in)));
    } catch (org.apache.thrift.TException te) {
      throw new java.io.IOException(te);
    }
  }

  private static class PlacarStandardSchemeFactory implements org.apache.thrift.scheme.SchemeFactory {
    public PlacarStandardScheme getScheme() {
      return new PlacarStandardScheme();
    }
  }

  private static class PlacarStandardScheme extends org.apache.thrift.scheme.StandardScheme<Placar> {

    public void read(org.apache.thrift.protocol.TProtocol iprot, Placar struct) throws org.apache.thrift.TException {
      org.apache.thrift.protocol.TField schemeField;
      iprot.readStructBegin();
      while (true)
      {
        schemeField = iprot.readFieldBegin();
        if (schemeField.type == org.apache.thrift.protocol.TType.STOP) { 
          break;
        }
        switch (schemeField.id) {
          case 1: // PLACAR
            if (schemeField.type == org.apache.thrift.protocol.TType.STRING) {
              struct.placar = iprot.readString();
              struct.setPlacarIsSet(true);
            } else { 
              org.apache.thrift.protocol.TProtocolUtil.skip(iprot, schemeField.type);
            }
            break;
          default:
            org.apache.thrift.protocol.TProtocolUtil.skip(iprot, schemeField.type);
        }
        iprot.readFieldEnd();
      }
      iprot.readStructEnd();

      // check for required fields of primitive type, which can't be checked in the validate method
      struct.validate();
    }

    public void write(org.apache.thrift.protocol.TProtocol oprot, Placar struct) throws org.apache.thrift.TException {
      struct.validate();

      oprot.writeStructBegin(STRUCT_DESC);
      if (struct.placar != null) {
        oprot.writeFieldBegin(PLACAR_FIELD_DESC);
        oprot.writeString(struct.placar);
        oprot.writeFieldEnd();
      }
      oprot.writeFieldStop();
      oprot.writeStructEnd();
    }

  }

  private static class PlacarTupleSchemeFactory implements org.apache.thrift.scheme.SchemeFactory {
    public PlacarTupleScheme getScheme() {
      return new PlacarTupleScheme();
    }
  }

  private static class PlacarTupleScheme extends org.apache.thrift.scheme.TupleScheme<Placar> {

    @Override
    public void write(org.apache.thrift.protocol.TProtocol prot, Placar struct) throws org.apache.thrift.TException {
      org.apache.thrift.protocol.TTupleProtocol oprot = (org.apache.thrift.protocol.TTupleProtocol) prot;
      oprot.writeString(struct.placar);
    }

    @Override
    public void read(org.apache.thrift.protocol.TProtocol prot, Placar struct) throws org.apache.thrift.TException {
      org.apache.thrift.protocol.TTupleProtocol iprot = (org.apache.thrift.protocol.TTupleProtocol) prot;
      struct.placar = iprot.readString();
      struct.setPlacarIsSet(true);
    }
  }

  private static <S extends org.apache.thrift.scheme.IScheme> S scheme(org.apache.thrift.protocol.TProtocol proto) {
    return (org.apache.thrift.scheme.StandardScheme.class.equals(proto.getScheme()) ? STANDARD_SCHEME_FACTORY : TUPLE_SCHEME_FACTORY).getScheme();
  }
}

